version: '3.4'

services:
  scrapingdsinterview:
    image: scrapingdsinterview
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 1p3a_interview_DS_US_scraper.py "]
    ports:
      - 5678:5678
